import { ethers } from 'ethers';

// EIP-712 domain for off-chain risk attestation signing.
// The signature is generated by the Risk Agent and verified off-chain before
// submitting the trade to Uniswap v4 on Base Sepolia. It is also stored in
// 0G Storage as a cryptographic audit trail.
const domain = {
  name:    'SwarmExecutorHook',
  version: '1',
  chainId: BigInt(84532), // Base Sepolia — must match the execution chain
  // Off-chain attestation: no verifying contract on-chain needed for Trade API path.
  // If a SwarmExecutorHook is deployed on Base Sepolia in the future, set this.
  verifyingContract: (process.env.HOOK_ADDRESS_SEPOLIA || '0x0000000000000000000000000000000000000000') as `0x${string}`,
};

const types = {
  RiskAttestation: [
    { name: 'sessionWallet',      type: 'address' },
    { name: 'tokenIn',            type: 'address' },
    { name: 'tokenOut',           type: 'address' },
    { name: 'maxSlippageBps',     type: 'uint256' },
    { name: 'maxAmountIn',        type: 'uint256' },
    { name: 'expiresAt',          type: 'uint256' },
    { name: 'swarmConsensusHash', type: 'bytes32'  },
  ],
};

export async function signRiskAttestation(
  riskAgentPrivateKey: string,
  attestation: Record<string, any>,
): Promise<string> {
  const wallet = new ethers.Wallet(riskAgentPrivateKey);
  return wallet.signTypedData(domain, types, attestation);
}
